//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBloodedFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HealthyD
    {

        public int ID { get; set; }
        [Required(ErrorMessage = "Please Enter Your Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter your email address")]
        [RegularExpression(".+\\@.+\\..+",
            ErrorMessage = "Please enter a VALID email address")]
        public string Email { get; set; }
        [Required(ErrorMessage ="Please enter a valid zip")]
        [StringLength(5, ErrorMessage = "Zip must be 5 digits")]
        public string Zip { get; set; }
        //public bool NewsRecv { get; set; }
    }
}
